require 'rodrinrj.options'
require 'rodrinrj.keymaps'
require 'rodrinrj.plugins'
require 'rodrinrj.impatient'
require 'rodrinrj.colorscheme'
require 'rodrinrj.cmp'
require 'rodrinrj.lsp'
require 'rodrinrj.telescope'
require 'rodrinrj.treesitter'
require 'rodrinrj.autopairs'
require 'rodrinrj.comment'
require 'rodrinrj.gitsigns'
require 'rodrinrj.nvim-tree'
require 'rodrinrj.bufferline'
require 'rodrinrj.lualine'
require 'rodrinrj.toggleterm'

